#############################################################################
# Makefile for building: AspeQt
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  aspeqt.pro
# Template: app
# Command: /usr/lib/qt/bin/qmake -o Makefile aspeqt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DVERSION=\"1.00.Preview_6\" -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=i686 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/qt/QtZlib -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/lib/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = AspeQt1.0.0
DISTDIR = /home/greblus/build/aspeqt-fork/.tmp/AspeQt1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro
LIBS          = $(SUBLIBS) -lz -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		sioworker.cpp \
		optionsdialog.cpp \
		aboutdialog.cpp \
		diskimage.cpp \
		diskimagepro.cpp \
		folderimage.cpp \
		miscdevices.cpp \
		createimagedialog.cpp \
		diskeditdialog.cpp \
		aspeqtsettings.cpp \
		autoboot.cpp \
		autobootdialog.cpp \
		atarifilesystem.cpp \
		miscutils.cpp \
		textprinterwindow.cpp \
		cassettedialog.cpp \
		docdisplaywindow.cpp \
		bootoptionsdialog.cpp \
		network.cpp \
		logdisplaydialog.cpp \
		serialport-unix.cpp qrc_icons.cpp \
		qrc_atarifiles.cpp \
		qrc_i18n.cpp \
		qrc_documentation.cpp \
		qrc_images.cpp \
		moc_mainwindow.cpp \
		moc_serialport.cpp \
		moc_sioworker.cpp \
		moc_optionsdialog.cpp \
		moc_aboutdialog.cpp \
		moc_diskimage.cpp \
		moc_diskimagepro.cpp \
		moc_folderimage.cpp \
		moc_miscdevices.cpp \
		moc_createimagedialog.cpp \
		moc_diskeditdialog.cpp \
		moc_autoboot.cpp \
		moc_autobootdialog.cpp \
		moc_atarifilesystem.cpp \
		moc_miscutils.cpp \
		moc_textprinterwindow.cpp \
		moc_cassettedialog.cpp \
		moc_docdisplaywindow.cpp \
		moc_bootoptionsdialog.cpp \
		moc_network.cpp \
		moc_logdisplaydialog.cpp \
		moc_serialport-unix.cpp
OBJECTS       = main.o \
		mainwindow.o \
		sioworker.o \
		optionsdialog.o \
		aboutdialog.o \
		diskimage.o \
		diskimagepro.o \
		folderimage.o \
		miscdevices.o \
		createimagedialog.o \
		diskeditdialog.o \
		aspeqtsettings.o \
		autoboot.o \
		autobootdialog.o \
		atarifilesystem.o \
		miscutils.o \
		textprinterwindow.o \
		cassettedialog.o \
		docdisplaywindow.o \
		bootoptionsdialog.o \
		network.o \
		logdisplaydialog.o \
		serialport-unix.o \
		qrc_icons.o \
		qrc_atarifiles.o \
		qrc_i18n.o \
		qrc_documentation.o \
		qrc_images.o \
		moc_mainwindow.o \
		moc_serialport.o \
		moc_sioworker.o \
		moc_optionsdialog.o \
		moc_aboutdialog.o \
		moc_diskimage.o \
		moc_diskimagepro.o \
		moc_folderimage.o \
		moc_miscdevices.o \
		moc_createimagedialog.o \
		moc_diskeditdialog.o \
		moc_autoboot.o \
		moc_autobootdialog.o \
		moc_atarifilesystem.o \
		moc_miscutils.o \
		moc_textprinterwindow.o \
		moc_cassettedialog.o \
		moc_docdisplaywindow.o \
		moc_bootoptionsdialog.o \
		moc_network.o \
		moc_logdisplaydialog.o \
		moc_serialport-unix.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/shell-unix.conf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_v8.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		aspeqt.pro mainwindow.h \
		serialport.h \
		sioworker.h \
		optionsdialog.h \
		aboutdialog.h \
		diskimage.h \
		diskimagepro.h \
		folderimage.h \
		miscdevices.h \
		createimagedialog.h \
		diskeditdialog.h \
		aspeqtsettings.h \
		autoboot.h \
		autobootdialog.h \
		atarifilesystem.h \
		miscutils.h \
		textprinterwindow.h \
		cassettedialog.h \
		docdisplaywindow.h \
		bootoptionsdialog.h \
		network.h \
		logdisplaydialog.h \
		serialport-unix.h main.cpp \
		mainwindow.cpp \
		sioworker.cpp \
		optionsdialog.cpp \
		aboutdialog.cpp \
		diskimage.cpp \
		diskimagepro.cpp \
		folderimage.cpp \
		miscdevices.cpp \
		createimagedialog.cpp \
		diskeditdialog.cpp \
		aspeqtsettings.cpp \
		autoboot.cpp \
		autobootdialog.cpp \
		atarifilesystem.cpp \
		miscutils.cpp \
		textprinterwindow.cpp \
		cassettedialog.cpp \
		docdisplaywindow.cpp \
		bootoptionsdialog.cpp \
		network.cpp \
		logdisplaydialog.cpp \
		serialport-unix.cpp
QMAKE_TARGET  = AspeQt
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = AspeQt


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h ui_optionsdialog.h ui_aboutdialog.h ui_createimagedialog.h ui_diskeditdialog.h ui_autobootdialog.h ui_textprinterwindow.h ui_cassettedialog.h ui_docdisplaywindow.h ui_bootoptionsdialog.h ui_logdisplaydialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: aspeqt.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/shell-unix.conf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_v8.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		aspeqt.pro \
		icons.qrc \
		atarifiles.qrc \
		i18n.qrc \
		documentation.qrc \
		images.qrc \
		/usr/lib/libQt5PrintSupport.prl \
		/usr/lib/libQt5Widgets.prl \
		/usr/lib/libQt5Gui.prl \
		/usr/lib/libQt5Core.prl \
		/usr/lib/libQt5Network.prl
	$(QMAKE) -o Makefile aspeqt.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/shell-unix.conf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_declarative.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_v8.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
aspeqt.pro:
icons.qrc:
atarifiles.qrc:
i18n.qrc:
documentation.qrc:
images.qrc:
/usr/lib/libQt5PrintSupport.prl:
/usr/lib/libQt5Widgets.prl:
/usr/lib/libQt5Gui.prl:
/usr/lib/libQt5Core.prl:
/usr/lib/libQt5Network.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile aspeqt.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents icons.qrc atarifiles.qrc i18n.qrc documentation.qrc images.qrc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h serialport.h sioworker.h optionsdialog.h aboutdialog.h diskimage.h diskimagepro.h folderimage.h miscdevices.h createimagedialog.h diskeditdialog.h aspeqtsettings.h autoboot.h autobootdialog.h atarifilesystem.h miscutils.h textprinterwindow.h cassettedialog.h docdisplaywindow.h bootoptionsdialog.h network.h logdisplaydialog.h serialport-unix.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp sioworker.cpp optionsdialog.cpp aboutdialog.cpp diskimage.cpp diskimagepro.cpp folderimage.cpp miscdevices.cpp createimagedialog.cpp diskeditdialog.cpp aspeqtsettings.cpp autoboot.cpp autobootdialog.cpp atarifilesystem.cpp miscutils.cpp textprinterwindow.cpp cassettedialog.cpp docdisplaywindow.cpp bootoptionsdialog.cpp network.cpp logdisplaydialog.cpp serialport-unix.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui optionsdialog.ui aboutdialog.ui createimagedialog.ui diskeditdialog.ui autobootdialog.ui textprinterwindow.ui cassettedialog.ui docdisplaywindow.ui bootoptionsdialog.ui logdisplaydialog.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_icons.cpp qrc_atarifiles.cpp qrc_i18n.cpp qrc_documentation.cpp qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp qrc_atarifiles.cpp qrc_i18n.cpp qrc_documentation.cpp qrc_images.cpp
qrc_icons.cpp: icons.qrc \
		silk-icons/icons/drive_disk.png \
		silk-icons/icons/folder.png \
		silk-icons/icons/font.png \
		silk-icons/icons/drive.png \
		silk-icons/icons/shape_square.png \
		silk-icons/icons/disconnect.png \
		silk-icons/icons/arrow_up.png \
		silk-icons/icons/delete.png \
		silk-icons/icons/drive_go.png \
		silk-icons/icons/drive_add.png \
		silk-icons/icons/page_white.png \
		silk-icons/icons/monitor.png \
		silk-icons/icons/printer.png \
		silk-icons/icons/lock.png \
		silk-icons/icons/add.png \
		silk-icons/icons/font_go.png \
		silk-icons/icons/page_white_text.png \
		silk-icons/icons/disk.png \
		silk-icons/icons/text_align_left.png \
		silk-icons/icons/lock_open.png \
		silk-icons/icons/page_white_go.png \
		silk-icons/icons/application.png \
		silk-icons/icons/drive_delete.png \
		silk-icons/icons/arrow_right.png \
		silk-icons/icons/connect.png \
		silk-icons/icons/drive_rename.png \
		silk-icons/icons/cut_red.png \
		silk-icons/icons/monitor_go.png \
		silk-icons/icons/page_white_c.png \
		silk-icons/icons/control_eject.png \
		silk-icons/icons/arrow_undo.png \
		silk-icons/icons/folder_edit.png \
		silk-icons/icons/printer_delete.png \
		other-icons/fuji.png \
		other-icons/move.png \
		other-icons/run.ico \
		other-icons/fade.png \
		oxygen-icons/16x16/actions/document_save_all.png \
		oxygen-icons/16x16/actions/network_connect.png \
		oxygen-icons/16x16/actions/network.png \
		oxygen-icons/16x16/actions/flag_red.png \
		oxygen-icons/16x16/actions/flag_green.png \
		oxygen-icons/16x16/actions/view_right_close.png \
		oxygen-icons/16x16/actions/format_font_size_more.png \
		oxygen-icons/16x16/actions/view_left_close.png \
		oxygen-icons/16x16/actions/exit.png \
		oxygen-icons/16x16/actions/help_about.png \
		oxygen-icons/16x16/actions/network_disconnect.png \
		oxygen-icons/16x16/actions/help_contents.png \
		oxygen-icons/16x16/devices/3floppy_mount.png \
		oxygen-icons/16x16/devices/media_tape.png \
		oxygen-icons/16x16/devices/printer1.png \
		oxygen-icons/16x16/devices/media_floppy.png \
		oxygen-icons/16x16/devices/3floppy_unmount.png \
		main-icon/AspeQt.ico \
		main-icon/main16.png
	/usr/lib/qt/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

qrc_atarifiles.cpp: atarifiles.qrc \
		atari/autoboot/autoboot.bin \
		atari/autoboot/autoboot-hispeed.bin
	/usr/lib/qt/bin/rcc -name atarifiles atarifiles.qrc -o qrc_atarifiles.cpp

qrc_i18n.cpp: i18n.qrc \
		i18n/qt_sk.qm \
		i18n/qt_de.qm \
		i18n/aspeqt_ru.qm \
		i18n/qt_pl.qm \
		i18n/aspeqt_es.qm \
		i18n/qt_ru.qm \
		i18n/aspeqt_tr.qm \
		i18n/qt_es.qm \
		i18n/qt_tr.qm \
		i18n/aspeqt_sk.qm \
		i18n/aspeqt_de.qm \
		i18n/aspeqt_pl.qm
	/usr/lib/qt/bin/rcc -name i18n i18n.qrc -o qrc_i18n.cpp

qrc_documentation.cpp: documentation.qrc \
		about.html \
		history.txt \
		license.txt
	/usr/lib/qt/bin/rcc -name documentation documentation.qrc -o qrc_documentation.cpp

qrc_images.cpp: images.qrc \
		images/MainWindowBackGround.png
	/usr/lib/qt/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_serialport.cpp moc_sioworker.cpp moc_optionsdialog.cpp moc_aboutdialog.cpp moc_diskimage.cpp moc_diskimagepro.cpp moc_folderimage.cpp moc_miscdevices.cpp moc_createimagedialog.cpp moc_diskeditdialog.cpp moc_autoboot.cpp moc_autobootdialog.cpp moc_atarifilesystem.cpp moc_miscutils.cpp moc_textprinterwindow.cpp moc_cassettedialog.cpp moc_docdisplaywindow.cpp moc_bootoptionsdialog.cpp moc_network.cpp moc_logdisplaydialog.cpp moc_serialport-unix.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_serialport.cpp moc_sioworker.cpp moc_optionsdialog.cpp moc_aboutdialog.cpp moc_diskimage.cpp moc_diskimagepro.cpp moc_folderimage.cpp moc_miscdevices.cpp moc_createimagedialog.cpp moc_diskeditdialog.cpp moc_autoboot.cpp moc_autobootdialog.cpp moc_atarifilesystem.cpp moc_miscutils.cpp moc_textprinterwindow.cpp moc_cassettedialog.cpp moc_docdisplaywindow.cpp moc_bootoptionsdialog.cpp moc_network.cpp moc_logdisplaydialog.cpp moc_serialport-unix.cpp
moc_mainwindow.cpp: optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		mainwindow.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_serialport.cpp: serialport-win32.h \
		serialport.h \
		serialport-unix.h \
		serialport.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include serialport.h -o moc_serialport.cpp

moc_sioworker.cpp: serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		sioworker.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include sioworker.h -o moc_sioworker.cpp

moc_optionsdialog.cpp: serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		optionsdialog.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include optionsdialog.h -o moc_optionsdialog.cpp

moc_aboutdialog.cpp: aboutdialog.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include aboutdialog.h -o moc_aboutdialog.cpp

moc_diskimage.cpp: sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		diskimage.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include diskimage.h -o moc_diskimage.cpp

moc_diskimagepro.cpp: diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		diskimagepro.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include diskimagepro.h -o moc_diskimagepro.cpp

moc_folderimage.cpp: diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		folderimage.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include folderimage.h -o moc_folderimage.cpp

moc_miscdevices.cpp: sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscdevices.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include miscdevices.h -o moc_miscdevices.cpp

moc_createimagedialog.cpp: createimagedialog.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include createimagedialog.h -o moc_createimagedialog.cpp

moc_diskeditdialog.cpp: atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		diskeditdialog.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include diskeditdialog.h -o moc_diskeditdialog.cpp

moc_autoboot.cpp: sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		autoboot.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include autoboot.h -o moc_autoboot.cpp

moc_autobootdialog.cpp: autobootdialog.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include autobootdialog.h -o moc_autobootdialog.cpp

moc_atarifilesystem.cpp: diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		atarifilesystem.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include atarifilesystem.h -o moc_atarifilesystem.cpp

moc_miscutils.cpp: miscutils.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include miscutils.h -o moc_miscutils.cpp

moc_textprinterwindow.cpp: textprinterwindow.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include textprinterwindow.h -o moc_textprinterwindow.cpp

moc_cassettedialog.cpp: sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		cassettedialog.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include cassettedialog.h -o moc_cassettedialog.cpp

moc_docdisplaywindow.cpp: docdisplaywindow.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include docdisplaywindow.h -o moc_docdisplaywindow.cpp

moc_bootoptionsdialog.cpp: bootoptionsdialog.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include bootoptionsdialog.h -o moc_bootoptionsdialog.cpp

moc_network.cpp: network.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include network.h -o moc_network.cpp

moc_logdisplaydialog.cpp: logdisplaydialog.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include logdisplaydialog.h -o moc_logdisplaydialog.cpp

moc_serialport-unix.cpp: serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		serialport-unix.h
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/greblus/build/aspeqt-fork -I/usr/include/qt/QtZlib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtCore -I/usr/include/c++/4.9.2 -I/usr/include/c++/4.9.2/i686-pc-linux-gnu -I/usr/include/c++/4.9.2/backward -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include -I/usr/local/include -I/usr/lib/gcc/i686-pc-linux-gnu/4.9.2/include-fixed -I/usr/include serialport-unix.h -o moc_serialport-unix.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_optionsdialog.h ui_aboutdialog.h ui_createimagedialog.h ui_diskeditdialog.h ui_autobootdialog.h ui_textprinterwindow.h ui_cassettedialog.h ui_docdisplaywindow.h ui_bootoptionsdialog.h ui_logdisplaydialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_optionsdialog.h ui_aboutdialog.h ui_createimagedialog.h ui_diskeditdialog.h ui_autobootdialog.h ui_textprinterwindow.h ui_cassettedialog.h ui_docdisplaywindow.h ui_bootoptionsdialog.h ui_logdisplaydialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_optionsdialog.h: optionsdialog.ui
	/usr/lib/qt/bin/uic optionsdialog.ui -o ui_optionsdialog.h

ui_aboutdialog.h: aboutdialog.ui
	/usr/lib/qt/bin/uic aboutdialog.ui -o ui_aboutdialog.h

ui_createimagedialog.h: createimagedialog.ui
	/usr/lib/qt/bin/uic createimagedialog.ui -o ui_createimagedialog.h

ui_diskeditdialog.h: diskeditdialog.ui
	/usr/lib/qt/bin/uic diskeditdialog.ui -o ui_diskeditdialog.h

ui_autobootdialog.h: autobootdialog.ui
	/usr/lib/qt/bin/uic autobootdialog.ui -o ui_autobootdialog.h

ui_textprinterwindow.h: textprinterwindow.ui
	/usr/lib/qt/bin/uic textprinterwindow.ui -o ui_textprinterwindow.h

ui_cassettedialog.h: cassettedialog.ui
	/usr/lib/qt/bin/uic cassettedialog.ui -o ui_cassettedialog.h

ui_docdisplaywindow.h: docdisplaywindow.ui
	/usr/lib/qt/bin/uic docdisplaywindow.ui -o ui_docdisplaywindow.h

ui_bootoptionsdialog.h: bootoptionsdialog.ui
	/usr/lib/qt/bin/uic bootoptionsdialog.ui -o ui_bootoptionsdialog.h

ui_logdisplaydialog.h: logdisplaydialog.ui
	/usr/lib/qt/bin/uic logdisplaydialog.ui -o ui_logdisplaydialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		ui_mainwindow.h \
		diskimagepro.h \
		folderimage.h \
		miscdevices.h \
		aspeqtsettings.h \
		autobootdialog.h \
		autoboot.h \
		cassettedialog.h \
		bootoptionsdialog.h \
		logdisplaydialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

sioworker.o: sioworker.cpp sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sioworker.o sioworker.cpp

optionsdialog.o: optionsdialog.cpp optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		ui_optionsdialog.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsdialog.o optionsdialog.cpp

aboutdialog.o: aboutdialog.cpp aboutdialog.h \
		ui_aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

diskimage.o: diskimage.cpp diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		aspeqtsettings.h \
		atarifilesystem.h \
		diskeditdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskimage.o diskimage.cpp

diskimagepro.o: diskimagepro.cpp diskimagepro.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskimagepro.o diskimagepro.cpp

folderimage.o: folderimage.cpp folderimage.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o folderimage.o folderimage.cpp

miscdevices.o: miscdevices.cpp miscdevices.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aspeqtsettings.h \
		mainwindow.h \
		optionsdialog.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o miscdevices.o miscdevices.cpp

createimagedialog.o: createimagedialog.cpp createimagedialog.h \
		ui_createimagedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o createimagedialog.o createimagedialog.cpp

diskeditdialog.o: diskeditdialog.cpp diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		ui_diskeditdialog.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskeditdialog.o diskeditdialog.cpp

aspeqtsettings.o: aspeqtsettings.cpp aspeqtsettings.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		mainwindow.h \
		optionsdialog.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aspeqtsettings.o aspeqtsettings.cpp

autoboot.o: autoboot.cpp autoboot.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autoboot.o autoboot.cpp

autobootdialog.o: autobootdialog.cpp autobootdialog.h \
		ui_autobootdialog.h \
		mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autobootdialog.o autobootdialog.cpp

atarifilesystem.o: atarifilesystem.cpp atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		diskeditdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o atarifilesystem.o atarifilesystem.cpp

miscutils.o: miscutils.cpp miscutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o miscutils.o miscutils.cpp

textprinterwindow.o: textprinterwindow.cpp textprinterwindow.h \
		ui_textprinterwindow.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textprinterwindow.o textprinterwindow.cpp

cassettedialog.o: cassettedialog.cpp cassettedialog.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		ui_cassettedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cassettedialog.o cassettedialog.cpp

docdisplaywindow.o: docdisplaywindow.cpp docdisplaywindow.h \
		ui_docdisplaywindow.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o docdisplaywindow.o docdisplaywindow.cpp

bootoptionsdialog.o: bootoptionsdialog.cpp bootoptionsdialog.h \
		ui_bootoptionsdialog.h \
		mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bootoptionsdialog.o bootoptionsdialog.cpp

network.o: network.cpp network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o network.o network.cpp

logdisplaydialog.o: logdisplaydialog.cpp logdisplaydialog.h \
		ui_logdisplaydialog.h \
		mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logdisplaydialog.o logdisplaydialog.cpp

serialport-unix.o: serialport-unix.cpp serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		sioworker.h \
		headers/atarisio.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialport-unix.o serialport-unix.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

qrc_atarifiles.o: qrc_atarifiles.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_atarifiles.o qrc_atarifiles.cpp

qrc_i18n.o: qrc_i18n.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_i18n.o qrc_i18n.cpp

qrc_documentation.o: qrc_documentation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_documentation.o qrc_documentation.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_serialport.o: moc_serialport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialport.o moc_serialport.cpp

moc_sioworker.o: moc_sioworker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sioworker.o moc_sioworker.cpp

moc_optionsdialog.o: moc_optionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsdialog.o moc_optionsdialog.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

moc_diskimage.o: moc_diskimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskimage.o moc_diskimage.cpp

moc_diskimagepro.o: moc_diskimagepro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskimagepro.o moc_diskimagepro.cpp

moc_folderimage.o: moc_folderimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_folderimage.o moc_folderimage.cpp

moc_miscdevices.o: moc_miscdevices.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_miscdevices.o moc_miscdevices.cpp

moc_createimagedialog.o: moc_createimagedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_createimagedialog.o moc_createimagedialog.cpp

moc_diskeditdialog.o: moc_diskeditdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskeditdialog.o moc_diskeditdialog.cpp

moc_autoboot.o: moc_autoboot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autoboot.o moc_autoboot.cpp

moc_autobootdialog.o: moc_autobootdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autobootdialog.o moc_autobootdialog.cpp

moc_atarifilesystem.o: moc_atarifilesystem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_atarifilesystem.o moc_atarifilesystem.cpp

moc_miscutils.o: moc_miscutils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_miscutils.o moc_miscutils.cpp

moc_textprinterwindow.o: moc_textprinterwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textprinterwindow.o moc_textprinterwindow.cpp

moc_cassettedialog.o: moc_cassettedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cassettedialog.o moc_cassettedialog.cpp

moc_docdisplaywindow.o: moc_docdisplaywindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_docdisplaywindow.o moc_docdisplaywindow.cpp

moc_bootoptionsdialog.o: moc_bootoptionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bootoptionsdialog.o moc_bootoptionsdialog.cpp

moc_network.o: moc_network.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_network.o moc_network.cpp

moc_logdisplaydialog.o: moc_logdisplaydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logdisplaydialog.o moc_logdisplaydialog.cpp

moc_serialport-unix.o: moc_serialport-unix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialport-unix.o moc_serialport-unix.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

