#############################################################################
# Makefile for building: AspeQt
# Generated by qmake (2.01a) (Qt 4.8.6) on: Tue May 12 20:28:24 2015
# Project:  aspeqt.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile aspeqt.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DVERSION=\"1.00.Preview_6\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtZlib -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lz -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		sioworker.cpp \
		optionsdialog.cpp \
		aboutdialog.cpp \
		diskimage.cpp \
		diskimagepro.cpp \
		folderimage.cpp \
		miscdevices.cpp \
		createimagedialog.cpp \
		diskeditdialog.cpp \
		aspeqtsettings.cpp \
		autoboot.cpp \
		autobootdialog.cpp \
		atarifilesystem.cpp \
		miscutils.cpp \
		textprinterwindow.cpp \
		cassettedialog.cpp \
		docdisplaywindow.cpp \
		bootoptionsdialog.cpp \
		network.cpp \
		logdisplaydialog.cpp \
		serialport-unix.cpp moc_mainwindow.cpp \
		moc_serialport.cpp \
		moc_sioworker.cpp \
		moc_optionsdialog.cpp \
		moc_aboutdialog.cpp \
		moc_diskimage.cpp \
		moc_diskimagepro.cpp \
		moc_folderimage.cpp \
		moc_miscdevices.cpp \
		moc_createimagedialog.cpp \
		moc_diskeditdialog.cpp \
		moc_autoboot.cpp \
		moc_autobootdialog.cpp \
		moc_atarifilesystem.cpp \
		moc_miscutils.cpp \
		moc_textprinterwindow.cpp \
		moc_cassettedialog.cpp \
		moc_docdisplaywindow.cpp \
		moc_bootoptionsdialog.cpp \
		moc_network.cpp \
		moc_logdisplaydialog.cpp \
		moc_serialport-unix.cpp \
		qrc_icons.cpp \
		qrc_atarifiles.cpp \
		qrc_i18n.cpp \
		qrc_documentation.cpp \
		qrc_images.cpp
OBJECTS       = main.o \
		mainwindow.o \
		sioworker.o \
		optionsdialog.o \
		aboutdialog.o \
		diskimage.o \
		diskimagepro.o \
		folderimage.o \
		miscdevices.o \
		createimagedialog.o \
		diskeditdialog.o \
		aspeqtsettings.o \
		autoboot.o \
		autobootdialog.o \
		atarifilesystem.o \
		miscutils.o \
		textprinterwindow.o \
		cassettedialog.o \
		docdisplaywindow.o \
		bootoptionsdialog.o \
		network.o \
		logdisplaydialog.o \
		serialport-unix.o \
		moc_mainwindow.o \
		moc_serialport.o \
		moc_sioworker.o \
		moc_optionsdialog.o \
		moc_aboutdialog.o \
		moc_diskimage.o \
		moc_diskimagepro.o \
		moc_folderimage.o \
		moc_miscdevices.o \
		moc_createimagedialog.o \
		moc_diskeditdialog.o \
		moc_autoboot.o \
		moc_autobootdialog.o \
		moc_atarifilesystem.o \
		moc_miscutils.o \
		moc_textprinterwindow.o \
		moc_cassettedialog.o \
		moc_docdisplaywindow.o \
		moc_bootoptionsdialog.o \
		moc_network.o \
		moc_logdisplaydialog.o \
		moc_serialport-unix.o \
		qrc_icons.o \
		qrc_atarifiles.o \
		qrc_i18n.o \
		qrc_documentation.o \
		qrc_images.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		aspeqt.pro
QMAKE_TARGET  = AspeQt
DESTDIR       = 
TARGET        = AspeQt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_optionsdialog.h ui_aboutdialog.h ui_createimagedialog.h ui_diskeditdialog.h ui_autobootdialog.h ui_textprinterwindow.h ui_cassettedialog.h ui_docdisplaywindow.h ui_bootoptionsdialog.h ui_logdisplaydialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: aspeqt.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile aspeqt.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile aspeqt.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/AspeQt1.0.0 || $(MKDIR) .tmp/AspeQt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/AspeQt1.0.0/ && $(COPY_FILE) --parents mainwindow.h serialport.h sioworker.h optionsdialog.h aboutdialog.h diskimage.h diskimagepro.h folderimage.h miscdevices.h createimagedialog.h diskeditdialog.h aspeqtsettings.h autoboot.h autobootdialog.h atarifilesystem.h miscutils.h textprinterwindow.h cassettedialog.h docdisplaywindow.h bootoptionsdialog.h network.h logdisplaydialog.h serialport-unix.h .tmp/AspeQt1.0.0/ && $(COPY_FILE) --parents icons.qrc atarifiles.qrc i18n.qrc documentation.qrc images.qrc .tmp/AspeQt1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp sioworker.cpp optionsdialog.cpp aboutdialog.cpp diskimage.cpp diskimagepro.cpp folderimage.cpp miscdevices.cpp createimagedialog.cpp diskeditdialog.cpp aspeqtsettings.cpp autoboot.cpp autobootdialog.cpp atarifilesystem.cpp miscutils.cpp textprinterwindow.cpp cassettedialog.cpp docdisplaywindow.cpp bootoptionsdialog.cpp network.cpp logdisplaydialog.cpp serialport-unix.cpp .tmp/AspeQt1.0.0/ && $(COPY_FILE) --parents mainwindow.ui optionsdialog.ui aboutdialog.ui createimagedialog.ui diskeditdialog.ui autobootdialog.ui textprinterwindow.ui cassettedialog.ui docdisplaywindow.ui bootoptionsdialog.ui logdisplaydialog.ui .tmp/AspeQt1.0.0/ && (cd `dirname .tmp/AspeQt1.0.0` && $(TAR) AspeQt1.0.0.tar AspeQt1.0.0 && $(COMPRESS) AspeQt1.0.0.tar) && $(MOVE) `dirname .tmp/AspeQt1.0.0`/AspeQt1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/AspeQt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_serialport.cpp moc_sioworker.cpp moc_optionsdialog.cpp moc_aboutdialog.cpp moc_diskimage.cpp moc_diskimagepro.cpp moc_folderimage.cpp moc_miscdevices.cpp moc_createimagedialog.cpp moc_diskeditdialog.cpp moc_autoboot.cpp moc_autobootdialog.cpp moc_atarifilesystem.cpp moc_miscutils.cpp moc_textprinterwindow.cpp moc_cassettedialog.cpp moc_docdisplaywindow.cpp moc_bootoptionsdialog.cpp moc_network.cpp moc_logdisplaydialog.cpp moc_serialport-unix.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_serialport.cpp moc_sioworker.cpp moc_optionsdialog.cpp moc_aboutdialog.cpp moc_diskimage.cpp moc_diskimagepro.cpp moc_folderimage.cpp moc_miscdevices.cpp moc_createimagedialog.cpp moc_diskeditdialog.cpp moc_autoboot.cpp moc_autobootdialog.cpp moc_atarifilesystem.cpp moc_miscutils.cpp moc_textprinterwindow.cpp moc_cassettedialog.cpp moc_docdisplaywindow.cpp moc_bootoptionsdialog.cpp moc_network.cpp moc_logdisplaydialog.cpp moc_serialport-unix.cpp
moc_mainwindow.cpp: optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_serialport.cpp: serialport-win32.h \
		serialport.h \
		serialport-unix.h \
		serialport.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) serialport.h -o moc_serialport.cpp

moc_sioworker.cpp: serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		sioworker.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sioworker.h -o moc_sioworker.cpp

moc_optionsdialog.cpp: serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		optionsdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) optionsdialog.h -o moc_optionsdialog.cpp

moc_aboutdialog.cpp: aboutdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) aboutdialog.h -o moc_aboutdialog.cpp

moc_diskimage.cpp: sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		diskimage.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) diskimage.h -o moc_diskimage.cpp

moc_diskimagepro.cpp: diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		diskimagepro.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) diskimagepro.h -o moc_diskimagepro.cpp

moc_folderimage.cpp: diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		folderimage.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) folderimage.h -o moc_folderimage.cpp

moc_miscdevices.cpp: sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscdevices.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) miscdevices.h -o moc_miscdevices.cpp

moc_createimagedialog.cpp: createimagedialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) createimagedialog.h -o moc_createimagedialog.cpp

moc_diskeditdialog.cpp: atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		diskeditdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) diskeditdialog.h -o moc_diskeditdialog.cpp

moc_autoboot.cpp: sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		autoboot.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) autoboot.h -o moc_autoboot.cpp

moc_autobootdialog.cpp: autobootdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) autobootdialog.h -o moc_autobootdialog.cpp

moc_atarifilesystem.cpp: diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		atarifilesystem.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) atarifilesystem.h -o moc_atarifilesystem.cpp

moc_miscutils.cpp: miscutils.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) miscutils.h -o moc_miscutils.cpp

moc_textprinterwindow.cpp: textprinterwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) textprinterwindow.h -o moc_textprinterwindow.cpp

moc_cassettedialog.cpp: sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		cassettedialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) cassettedialog.h -o moc_cassettedialog.cpp

moc_docdisplaywindow.cpp: docdisplaywindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) docdisplaywindow.h -o moc_docdisplaywindow.cpp

moc_bootoptionsdialog.cpp: bootoptionsdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) bootoptionsdialog.h -o moc_bootoptionsdialog.cpp

moc_network.cpp: network.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) network.h -o moc_network.cpp

moc_logdisplaydialog.cpp: logdisplaydialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) logdisplaydialog.h -o moc_logdisplaydialog.cpp

moc_serialport-unix.cpp: serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		serialport-unix.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) serialport-unix.h -o moc_serialport-unix.cpp

compiler_rcc_make_all: qrc_icons.cpp qrc_atarifiles.cpp qrc_i18n.cpp qrc_documentation.cpp qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp qrc_atarifiles.cpp qrc_i18n.cpp qrc_documentation.cpp qrc_images.cpp
qrc_icons.cpp: icons.qrc \
		oxygen-icons/16x16/actions/help_contents.png \
		oxygen-icons/16x16/actions/document_save_all.png \
		oxygen-icons/16x16/actions/format_font_size_more.png \
		oxygen-icons/16x16/actions/network_disconnect.png \
		oxygen-icons/16x16/actions/exit.png \
		oxygen-icons/16x16/actions/network_connect.png \
		oxygen-icons/16x16/actions/view_left_close.png \
		oxygen-icons/16x16/actions/flag_red.png \
		oxygen-icons/16x16/actions/view_right_close.png \
		oxygen-icons/16x16/actions/network.png \
		oxygen-icons/16x16/actions/flag_green.png \
		oxygen-icons/16x16/actions/help_about.png \
		oxygen-icons/16x16/devices/media_floppy.png \
		oxygen-icons/16x16/devices/3floppy_unmount.png \
		oxygen-icons/16x16/devices/printer1.png \
		oxygen-icons/16x16/devices/3floppy_mount.png \
		oxygen-icons/16x16/devices/media_tape.png \
		other-icons/run.ico \
		other-icons/move.png \
		other-icons/fuji.png \
		other-icons/fade.png \
		main-icon/main16.png \
		main-icon/AspeQt.ico \
		silk-icons/icons/drive_rename.png \
		silk-icons/icons/text_align_left.png \
		silk-icons/icons/drive.png \
		silk-icons/icons/printer_delete.png \
		silk-icons/icons/application.png \
		silk-icons/icons/add.png \
		silk-icons/icons/folder.png \
		silk-icons/icons/disk.png \
		silk-icons/icons/monitor_go.png \
		silk-icons/icons/arrow_right.png \
		silk-icons/icons/folder_edit.png \
		silk-icons/icons/delete.png \
		silk-icons/icons/shape_square.png \
		silk-icons/icons/drive_go.png \
		silk-icons/icons/monitor.png \
		silk-icons/icons/font_go.png \
		silk-icons/icons/printer.png \
		silk-icons/icons/connect.png \
		silk-icons/icons/lock.png \
		silk-icons/icons/arrow_undo.png \
		silk-icons/icons/control_eject.png \
		silk-icons/icons/drive_disk.png \
		silk-icons/icons/disconnect.png \
		silk-icons/icons/page_white.png \
		silk-icons/icons/font.png \
		silk-icons/icons/drive_delete.png \
		silk-icons/icons/cut_red.png \
		silk-icons/icons/page_white_text.png \
		silk-icons/icons/lock_open.png \
		silk-icons/icons/arrow_up.png \
		silk-icons/icons/drive_add.png \
		silk-icons/icons/page_white_go.png \
		silk-icons/icons/page_white_c.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

qrc_atarifiles.cpp: atarifiles.qrc \
		atari/autoboot/autoboot.bin \
		atari/autoboot/autoboot-hispeed.bin
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name atarifiles atarifiles.qrc -o qrc_atarifiles.cpp

qrc_i18n.cpp: i18n.qrc \
		i18n/aspeqt_pl.qm \
		i18n/aspeqt_ru.qm \
		i18n/aspeqt_es.qm \
		i18n/qt_ru.qm \
		i18n/aspeqt_de.qm \
		i18n/qt_de.qm \
		i18n/aspeqt_tr.qm \
		i18n/qt_tr.qm \
		i18n/qt_es.qm \
		i18n/qt_pl.qm \
		i18n/aspeqt_sk.qm \
		i18n/qt_sk.qm
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name i18n i18n.qrc -o qrc_i18n.cpp

qrc_documentation.cpp: documentation.qrc \
		about.html \
		history.txt \
		license.txt
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name documentation documentation.qrc -o qrc_documentation.cpp

qrc_images.cpp: images.qrc \
		images/MainWindowBackGround.png
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_optionsdialog.h ui_aboutdialog.h ui_createimagedialog.h ui_diskeditdialog.h ui_autobootdialog.h ui_textprinterwindow.h ui_cassettedialog.h ui_docdisplaywindow.h ui_bootoptionsdialog.h ui_logdisplaydialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_optionsdialog.h ui_aboutdialog.h ui_createimagedialog.h ui_diskeditdialog.h ui_autobootdialog.h ui_textprinterwindow.h ui_cassettedialog.h ui_docdisplaywindow.h ui_bootoptionsdialog.h ui_logdisplaydialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_optionsdialog.h: optionsdialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic optionsdialog.ui -o ui_optionsdialog.h

ui_aboutdialog.h: aboutdialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic aboutdialog.ui -o ui_aboutdialog.h

ui_createimagedialog.h: createimagedialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic createimagedialog.ui -o ui_createimagedialog.h

ui_diskeditdialog.h: diskeditdialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic diskeditdialog.ui -o ui_diskeditdialog.h

ui_autobootdialog.h: autobootdialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic autobootdialog.ui -o ui_autobootdialog.h

ui_textprinterwindow.h: textprinterwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic textprinterwindow.ui -o ui_textprinterwindow.h

ui_cassettedialog.h: cassettedialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic cassettedialog.ui -o ui_cassettedialog.h

ui_docdisplaywindow.h: docdisplaywindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic docdisplaywindow.ui -o ui_docdisplaywindow.h

ui_bootoptionsdialog.h: bootoptionsdialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic bootoptionsdialog.ui -o ui_bootoptionsdialog.h

ui_logdisplaydialog.h: logdisplaydialog.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic logdisplaydialog.ui -o ui_logdisplaydialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h \
		ui_mainwindow.h \
		diskimagepro.h \
		folderimage.h \
		miscdevices.h \
		aspeqtsettings.h \
		autobootdialog.h \
		autoboot.h \
		cassettedialog.h \
		bootoptionsdialog.h \
		logdisplaydialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

sioworker.o: sioworker.cpp sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sioworker.o sioworker.cpp

optionsdialog.o: optionsdialog.cpp optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		ui_optionsdialog.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optionsdialog.o optionsdialog.cpp

aboutdialog.o: aboutdialog.cpp aboutdialog.h \
		ui_aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

diskimage.o: diskimage.cpp diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		aspeqtsettings.h \
		atarifilesystem.h \
		diskeditdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskimage.o diskimage.cpp

diskimagepro.o: diskimagepro.cpp diskimagepro.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskimagepro.o diskimagepro.cpp

folderimage.o: folderimage.cpp folderimage.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o folderimage.o folderimage.cpp

miscdevices.o: miscdevices.cpp miscdevices.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aspeqtsettings.h \
		mainwindow.h \
		optionsdialog.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o miscdevices.o miscdevices.cpp

createimagedialog.o: createimagedialog.cpp createimagedialog.h \
		ui_createimagedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o createimagedialog.o createimagedialog.cpp

diskeditdialog.o: diskeditdialog.cpp diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		ui_diskeditdialog.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o diskeditdialog.o diskeditdialog.cpp

aspeqtsettings.o: aspeqtsettings.cpp aspeqtsettings.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		mainwindow.h \
		optionsdialog.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aspeqtsettings.o aspeqtsettings.cpp

autoboot.o: autoboot.cpp autoboot.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autoboot.o autoboot.cpp

autobootdialog.o: autobootdialog.cpp autobootdialog.h \
		ui_autobootdialog.h \
		mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o autobootdialog.o autobootdialog.cpp

atarifilesystem.o: atarifilesystem.cpp atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		miscutils.h \
		diskeditdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o atarifilesystem.o atarifilesystem.cpp

miscutils.o: miscutils.cpp miscutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o miscutils.o miscutils.cpp

textprinterwindow.o: textprinterwindow.cpp textprinterwindow.h \
		ui_textprinterwindow.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textprinterwindow.o textprinterwindow.cpp

cassettedialog.o: cassettedialog.cpp cassettedialog.h \
		sioworker.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		ui_cassettedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cassettedialog.o cassettedialog.cpp

docdisplaywindow.o: docdisplaywindow.cpp docdisplaywindow.h \
		ui_docdisplaywindow.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o docdisplaywindow.o docdisplaywindow.cpp

bootoptionsdialog.o: bootoptionsdialog.cpp bootoptionsdialog.h \
		ui_bootoptionsdialog.h \
		mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bootoptionsdialog.o bootoptionsdialog.cpp

network.o: network.cpp network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o network.o network.cpp

logdisplaydialog.o: logdisplaydialog.cpp logdisplaydialog.h \
		ui_logdisplaydialog.h \
		mainwindow.h \
		optionsdialog.h \
		serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		aboutdialog.h \
		createimagedialog.h \
		diskeditdialog.h \
		atarifilesystem.h \
		diskimage.h \
		sioworker.h \
		miscutils.h \
		textprinterwindow.h \
		docdisplaywindow.h \
		network.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logdisplaydialog.o logdisplaydialog.cpp

serialport-unix.o: serialport-unix.cpp serialport.h \
		serialport-win32.h \
		serialport-unix.h \
		sioworker.h \
		headers/atarisio.h \
		aspeqtsettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialport-unix.o serialport-unix.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_serialport.o: moc_serialport.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialport.o moc_serialport.cpp

moc_sioworker.o: moc_sioworker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sioworker.o moc_sioworker.cpp

moc_optionsdialog.o: moc_optionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optionsdialog.o moc_optionsdialog.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

moc_diskimage.o: moc_diskimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskimage.o moc_diskimage.cpp

moc_diskimagepro.o: moc_diskimagepro.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskimagepro.o moc_diskimagepro.cpp

moc_folderimage.o: moc_folderimage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_folderimage.o moc_folderimage.cpp

moc_miscdevices.o: moc_miscdevices.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_miscdevices.o moc_miscdevices.cpp

moc_createimagedialog.o: moc_createimagedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_createimagedialog.o moc_createimagedialog.cpp

moc_diskeditdialog.o: moc_diskeditdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_diskeditdialog.o moc_diskeditdialog.cpp

moc_autoboot.o: moc_autoboot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autoboot.o moc_autoboot.cpp

moc_autobootdialog.o: moc_autobootdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_autobootdialog.o moc_autobootdialog.cpp

moc_atarifilesystem.o: moc_atarifilesystem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_atarifilesystem.o moc_atarifilesystem.cpp

moc_miscutils.o: moc_miscutils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_miscutils.o moc_miscutils.cpp

moc_textprinterwindow.o: moc_textprinterwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textprinterwindow.o moc_textprinterwindow.cpp

moc_cassettedialog.o: moc_cassettedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cassettedialog.o moc_cassettedialog.cpp

moc_docdisplaywindow.o: moc_docdisplaywindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_docdisplaywindow.o moc_docdisplaywindow.cpp

moc_bootoptionsdialog.o: moc_bootoptionsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bootoptionsdialog.o moc_bootoptionsdialog.cpp

moc_network.o: moc_network.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_network.o moc_network.cpp

moc_logdisplaydialog.o: moc_logdisplaydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_logdisplaydialog.o moc_logdisplaydialog.cpp

moc_serialport-unix.o: moc_serialport-unix.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_serialport-unix.o moc_serialport-unix.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

qrc_atarifiles.o: qrc_atarifiles.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_atarifiles.o qrc_atarifiles.cpp

qrc_i18n.o: qrc_i18n.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_i18n.o qrc_i18n.cpp

qrc_documentation.o: qrc_documentation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_documentation.o qrc_documentation.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

